#!/usr/bin/env python3
"""
promote_to_runbook.py — Auto-updates RUNBOOK.md from learning_events.jsonl.

Each entry in data/learning_events.jsonl is { ts, symptom, action, result }.
This script:
  - Appends recent (unseen) events to RUNBOOK.md "Recent recoveries" section.
  - Groups events by (symptom_family, result) and promotes a pattern to
    "Confirmed patterns" once it has been seen N times.
  - Keeps the file deterministic and idempotent — re-running is safe.

The cursor of "already-processed" events is stored at
data/.runbook_cursor.json (last_ts).

Run from launchd hourly OR after each successful auto-recovery.
"""
from __future__ import annotations

import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
EVENTS = DATA / "learning_events.jsonl"
CURSOR = DATA / ".runbook_cursor.json"
RUNBOOK = ROOT / "RUNBOOK.md"

PROMOTE_THRESHOLD = 3  # N occurrences before a pattern is "confirmed"


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load_cursor() -> str:
    if CURSOR.exists():
        try:
            return json.loads(CURSOR.read_text()).get("last_ts", "")
        except Exception:
            return ""
    return ""


def save_cursor(ts: str) -> None:
    CURSOR.write_text(json.dumps({"last_ts": ts}))


def symptom_family(symptom: str) -> str:
    """Coarse-grain a symptom string into a family for grouping."""
    s = (symptom or "").lower()
    if "billing" in s:
        return "gh_actions_billing"
    if "heartbeat_lag" in s or "lag_min" in s:
        return "sync_lag"
    if "supa" in s or "supabase" in s:
        return "supabase_fetch"
    if "creds" in s:
        return "creds_missing"
    if "local_mirror" in s:
        return "local_mirror_fallback"
    if "recovery" in s:
        return "recovery_attempt"
    return s.split("=")[0] or "other"


def load_all_events() -> list[dict]:
    if not EVENTS.exists():
        return []
    out = []
    with EVENTS.open() as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except Exception:
                continue
    out.sort(key=lambda e: e.get("ts", ""))
    return out


def render_runbook(events: list[dict]) -> str:
    families: dict[str, list[dict]] = defaultdict(list)
    for e in events:
        families[symptom_family(e.get("symptom", ""))].append(e)

    confirmed = [(f, evs) for f, evs in families.items() if len(evs) >= PROMOTE_THRESHOLD]
    confirmed.sort(key=lambda x: -len(x[1]))

    recent = sorted(events, key=lambda e: e.get("ts", ""), reverse=True)[:20]

    lines: list[str] = []
    lines.append("# RUNBOOK — Battle of Bots sync recovery")
    lines.append("")
    lines.append("> Auto-generated by `promote_to_runbook.py`. Do NOT edit by hand.")
    lines.append(f"> Last update: `{now_iso()}` · Events tracked: {len(events)}")
    lines.append("")

    lines.append("## Confirmed patterns")
    lines.append("")
    if not confirmed:
        lines.append(f"_No pattern has reached the threshold of {PROMOTE_THRESHOLD} occurrences yet._")
        lines.append("")
    else:
        for family, evs in confirmed:
            results = defaultdict(int)
            for e in evs:
                results[e.get("result", "?")] += 1
            outcome = ", ".join(f"{k}={v}" for k, v in sorted(results.items()))
            first = evs[0].get("ts", "?")
            last = evs[-1].get("ts", "?")
            sample_actions = list({(e.get("action") or "")[:80] for e in evs})[:3]
            lines.append(f"### {family}")
            lines.append(f"- **Occurrences:** {len(evs)} (first `{first}`, last `{last}`)")
            lines.append(f"- **Outcomes:** {outcome}")
            lines.append("- **Sample actions:**")
            for a in sample_actions:
                lines.append(f"  - `{a}`")
            if family == "gh_actions_billing":
                lines.append("- **Resolution path:** restore billing at https://github.com/settings/billing → heartbeat will recover on next 10-min tick.")
            elif family == "sync_lag":
                lines.append("- **Resolution path:** dispatch_refresh.py was triggered; check `data/dispatch_refresh_log.jsonl` for outcome.")
            elif family == "supabase_fetch":
                lines.append("- **Resolution path:** check Supabase status + verify SUPABASE_SERVICE_ROLE_KEY in `.env.local` is current.")
            elif family == "creds_missing":
                lines.append("- **Resolution path:** ensure `.env.local` exists with SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY (chmod 600).")
            elif family == "local_mirror_fallback":
                lines.append("- **Resolution path:** Mac executed mirror.sh as last-resort; verify Tailscale + SSH key reachable.")
            lines.append("")

    lines.append("## Recent recoveries (last 20)")
    lines.append("")
    if not recent:
        lines.append("_No events recorded yet._")
        lines.append("")
    else:
        lines.append("| ts | symptom | action | result |")
        lines.append("|----|---------|--------|--------|")
        for e in recent:
            ts = e.get("ts", "?")
            sym = (e.get("symptom") or "")[:60]
            act = (e.get("action") or "")[:80]
            res = e.get("result") or "?"
            lines.append(f"| `{ts}` | {sym} | `{act}` | {res} |")
        lines.append("")

    lines.append("## How recoveries flow")
    lines.append("")
    lines.append("1. `heartbeat_check.py` (Mac launchd, 10 min) detects lag > 65 min.")
    lines.append("2. Sends FAIL email + spawns `dispatch_refresh.py`.")
    lines.append("3. `dispatch_refresh.py` triggers GH `repository_dispatch`, waits 4 min, re-checks Supabase.")
    lines.append("4. Up to 3 attempts; if all fail OR billing-blocked, sends \"manual intervention\" email.")
    lines.append("5. Each step appends to `data/learning_events.jsonl` and this RUNBOOK regenerates.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    events = load_all_events()
    body = render_runbook(events)
    tmp = RUNBOOK.with_suffix(".md.tmp")
    tmp.write_text(body, encoding="utf-8")
    tmp.replace(RUNBOOK)
    if events:
        save_cursor(events[-1].get("ts", ""))
    print(f"[runbook] events={len(events)} written={RUNBOOK.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
